

# Profile Configuration
#
# Purpose: Centralized configuration for profile data
#
# Structure:
# - Personal information (name, tagline, email, avatar)
# - Social media links
# - Projects with GitHub integration
# - Experience timeline
# - Education history
# - Tech stack
#
# Usage:
# - Imported by various components to render profile content
# - Supports markdown for rich text formatting
# - Enables easy content updates without code changessections:
  profile: 1
  intro: 2
  projects: 3
  experiences: 4
  techStacks: 5
  education: 6

profile:
  name: Steven Lynn
  tagline: 🤖 AI Dev | 📷 Amateur Landscape Photographer
  email: i@stv.pm
  avatar: /avatar.jpg
  socialMedia:
    - platform: GitHub
      url: https://github.com/stvlynn
    - platform: Twitter
      url: https://twitter.com/stvlynn
    - platform: LinkedIn
      url: https://www.linkedin.com/in/hongyi-ling-420346285


## Intro
intro:
  content: ./intro.md

projects:
  - name: Twi.am
    description: A Twitter MBTI personality analysis tool that infers users' personality types through their Twitter behavior, combining social media analytics with psychological theories.
    image: /projects/twi-am.png
    url: https://github.com/stvlynn/twi.am
    tech: [Next.js, TailwindCSS, Twitter API]

  - name: Modify
    description: A mobile chat application built on the Dify AI platform, providing an intuitive interface for AI-powered conversations and natural language interactions.
    image: /projects/modify.png
    url: https://github.com/stvlynn/modify
    tech: [React Native, Dify API, TypeScript]

  - name: Flashcard
    description: An open-source alternative to Duolingo, featuring a modern UI and multi-language support for intelligent language learning through AI-powered flashcards.
    image: /projects/flashcard.png
    url: https://github.com/stvlynn/flashcard
    tech: [Next.js, TailwindCSS, Dify API]

  - name: EasyReceiptSwift
    description: A Swift-based iOS app that uses LLM vision technology to scan receipts and automatically sync the data to Feishu or Google Sheets.
    image: /projects/easyreceipt.png
    url: https://github.com/stvlynn/EasyReceiptSwift
    tech: [Swift, Vision API, Google Sheets API]

  - name: TwitterInstantPortrait
    description: An AI-powered tool that generates instant artistic portraits from Twitter profile pictures, combining computer vision with artistic style transfer.
    image: /projects/portrait.png
    url: https://github.com/stvlynn/TwitterInstantPortrait
    tech: [Python, TensorFlow, Twitter API]

  - name: TwitterYearlyKanji
    description: A data visualization project that analyzes and displays the most frequently used Kanji characters on Twitter throughout the year.
    image: /projects/kanji.png
    url: https://github.com/stvlynn/TwitterYearlyKanji
    tech: [D3.js, Node.js, Twitter API]

  - name: LangFixer
    description: A tool for checking and maintaining consistency between multiple language versions of text, helping developers and content creators manage multilingual content.
    image: /projects/langfixer.png
    url: https://github.com/stvlynn/langfixer
    tech: [TypeScript, i18n, React]

experiences:
  - company: Dify
    position: Community Operations Associate
    period: 2024.9 - Present
    description: Building usecases for Dify. Maintaining community health and growth.
    image: /experiences/dify.png

techStacks:
  - name: React
    proficiency: 3
    icon: react
  - name: TypeScript
    proficiency: 3
    icon: typescript
  - name: Node.js
    proficiency: 3
    icon: nodejs
  - name: Python
    proficiency: 2
    icon: python

education:
  - institution: Nanjing Forestry University
    degree: Bachelor of Engineering
    period: 2021 - Present
    description: Majoring in Machanical Engineering
    image: https://images.unsplash.com/photo-1616079482812-62c95cd27ea7