# Profile Configuration

# Personal Info
personal:
  avatar: '/assets/avatar.jpg'  # Path to your avatar image
  name: 'Steven Lynn'
  description: 'AI Dev & Technical Writer'
  email: 'stvlynn@dify.ai'  # Optional
  phone: ''    # Optional
  social:
    github: 'stvlynn'        # Optional
    twitter: 'stv_lynn'       # Optional
    linkedin: ''      # Optional
    facebook: ''      # Optional
    telegram: 'stvlynn'      # Optional
  position: 0

# About Me
about:
  title: 'Intro'
  description: 'A university student. Intership @Dify. Focusing on LLM agents development.'
  position: 1

# Technical Skills
skills:
  title: 'Skills'
  abilities:
    - vuejs
    - python
    - matlab
    - docker
    - linux
  position: 2

# Projects
projects:
  title: 'Projects'
  items:
    - title: 'Twi.am - Twitter MBTI Receipt'
      description: 'A website generates receipt-style analysis of your MBTI using data scraped from twitter profile.'
      tags: ['Vue3', 'TailwindCSS', 'LLM']
    - title: 'EasyReceipt'
      description: 'An iOS APP that helps you scan receipts using LLM vision and sync to Feishu.'
      tags: ['Swift', 'LLM']
    - title: 'Reflection-Chinese-32B'
      description: 'A fine-tuned LLM with CoT.'
      tags: ['LLM']
  position: 3

# Education (Optional)
education:
  title: '教育经历'
  items:
    - school: '示例大学'
      time: '2015-2019'
    - school: '示例研究生院'
      time: '2019-2022'
  position: 0

# Links (Optional)
links:
  title: 'Link'
  items:
    - name: 'Blog'
      url: 'https://blog.stv.pm'
      avatar: '/assets/blog-avatar.png'
      position: 4
